services:
  - type: web
    name: skypulse-weather
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: H2_CONSOLE_ENABLED
        value: "false"
    healthCheckPath: /actuator/health
